### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by mecca831** [cesquivias/bf-graal#2]
This is more of a question. I implemented a simple BF interpreter with a switch statement. I want to see if Graal/Truffle with its JIT capability can improve the performance. To my surprise, the result is mostly the same, if not worse. Is it because the program is too simple for JIT to be effective? Do you have a similar observation?

Test file: https://github.com/brain-lang/brainfuck/blob/master/examples/mandel.bf

bf-graal:
```
time ./bf mandel.bf
...
real	2m4.982s
user	3m49.124s
sys	0m5.065s
```

My interpreter:
```
time java -jar build/libs/bf-interpreter.jar mandel.bf
real	2m10.366s
user	1m53.874s
sys	0m4.346s
```

**Comment by cesquivias** [comment]
The JIT requires more than one pass to really kick in. Try running 10 iterations in succession and the  last few should render a lot faster than the first.

With bf-graal, try
```
./bf -n 10 mandel.bf
```

That flag means your script will run 10 times in the same VM instance so there's plenty of opportunity for the JIT to kick in

**Comment by mecca831** [comment]
Thanks for the tip! The subsequent runs are much faster after the JIT kicks in.
